### ISSUE TITLE
returnTradeHistory returns type buy only

### ISSUE THREAD

**Issue by bitdjinn** [AuroraDAO/idex-api-docs#18] opened 2018-06-01 09:53 UTC
when using the returnTradeHistory with an address parameter. Result "type" is always set to "buy" even if its a sell.

**Comment by fubar** [comment] 2018-07-07 00:46
@bitdjinn I can't reproduce this; please provide a sample request and response with an explanation which parts of the response you expect to be different. Note that as per docs, "the `type` property of the trade objects will refer to the action on the market taken relative to the user, not relative to the market". See https://github.com/AuroraDAO/idex-api-docs#returntradehistory

Closing this issue; let me know if you need more assistance.

**Closed by fubar** 2018-07-07 00:46 UTC

**Comment by bitdjinn** [comment] 2018-07-09 10:51
The issue is still unresolved, the trades returned by returnTradeHistory doesn't mimic the My Trades section of the IDEX appication. Trades of type "Sell" (showing Sell in My Trades") are still returned as "buy" in the api response when using the address parameter. Where do I submit **non public** screenshots, responses and requests?

**Comment by salty82** [comment] 2018-08-03 12:49
I’m seeing the same issue. Is this being looked at as this issue is closed?

I’m trying to reconcile the activity (deposits, withdrawals, trades, fees, etc) and nothing is making sense via the trade history endpoint on the api.
