### ISSUE TITLE
lowestAsk and highestBid

### ISSUE THREAD

**Issue by Ppantich** [AuroraDAO/idex-api-docs#30] opened 2018-07-02 00:51 UTC
lowestAsk and highestBid from ticker return not current lowest ask and highest bid as in most of all exchanges but seems like lowest and highest for 24 hr. Is it correct behaviour? It is more useful to have current values.

**Comment by rfenzo** [comment] 2018-07-05 11:00
This api is disabled

**Comment by Ppantich** [comment] 2018-07-07 00:35
@fubar Current values I mean current lowestAsk and highestBid from orderbook right now. That is standard behaviour for almost all exchanges.

**Comment by fubar** [comment] 2018-07-07 00:38
@Ppantich In other words, take lowestAsk and highestBid from orders regardless of their age, even if an order is older than 24 hours?

**Comment by Ppantich** [comment] 2018-07-07 00:59
@fubar Yes, it is like the best offer to buy or sell right now.

**Comment by fubar** [comment] 2018-07-07 01:06
@Ppantich Actually, that is already the case - lowestAsk and highestBid values of a ticker are based on all open orders, regardless of age. Closing this issue.

**Comment by Ppantich** [comment] 2018-07-07 01:13
@fubar Really? Did you check it before closing the issue? Just compare https://api.idex.market/returnTicker and any orderbook?

**Comment by Ppantich** [comment] 2018-07-07 01:34
@fubar For example, in ticker
["ETH_AUC"]=> array(8) { ["last"]=> string(20) "0.000335548546214117" ["high"]=> string(20) "0.000356583360869493" ["low"]=> string(20) "0.000320556833044118" ["lowestAsk"]=> string(20) "0.000337273453138036" ["highestBid"]=> string(20) "0.000532759002514383" ["percentChange"]=> string(10) "0.78586527" ["baseVolume"]=> string(19) "8.98462428185177987" ["quoteVolume"]=> string(24) "26529.220336063443977933"
in orderbook lowestAsk is 0.00034624, highestBid is 0.00033394

**Comment by fubar** [comment] 2018-07-07 02:06
Thanks @Ppantich, I was able to reproduce it for that market. It is now fixed for the time being. We'll look into the cause of the inconsistency. In the meantime please let me know if you notice such an inconsistency again!

**Closed** 2018-07-18 00:23 UTC
